---
title: "Problem Set 3 Delgado, Romero, Castillo"
author: "Sergio Delgado, Daniel Romero, Carlos Castillo"
date: "2023-12-08"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Punto 1

```{r}
## initial setup
rm(list=ls())
require(pacman)
p_load(tidyverse,rio,data.table)

## Punto 1.1
rutas <- list.files("input/" , recursive=T , full.names=T)

## Punto 1.2 

## Extraer las rutas
rutas_resto <- str_subset(string = rutas , pattern = "Resto - Ca")

## Cargar en lista
lista_resto <- import_list(file = rutas_resto)

## Textear la cadena de caracteres 
rutas_resto[1]
str_sub(rutas_resto[35],start = 14 , 17)

## Agregar ruta
View(lista_resto[[1]])
lista_resto[[1]]$path <- rutas_resto[1]

## Aplicar loop  
for (i in 1:length(lista_resto)){
  lista_resto[[i]]$path <- rutas_resto[i]  
  lista_resto[[i]]$year <- str_sub(lista_resto[[i]]$path,start = 14 , 17)
}
View(lista_resto[[20]])

## Punto 1.3
lista_resto[[36]] <- NULL
df_resto <- rbindlist(l=lista_resto , use.names=T , fill=T)

## export
export(df_resto,"/output/db_full.rds")
```

##Punto 2

primero realizamos una visualización de un gráfico de barras que muestre la diferencia en proporción entre honbres y mujeres en los hogares colombianos

```{r pressure, echo=FALSE}
rm(list=ls())

install.packages(ggplot2)

library(ggplot2)

df_resto <- import("/output/db_full.rds")

graph_1 <- df_resto %>% 
  group_by(P6020) %>% 
  summarise(promedio = mean(P6050, na.rm = TRUE)) %>% 
  ggplot(data = . , mapping = aes(x = as.factor(P6020) , y = promedio, fill = as.factor(P6020))) + 
  geom_bar(stat = "identity") + 
  scale_fill_manual(values = c("2" = "red", "1" = "blue"), label = c("1" = "Hombre", "2" = "Mujer"), name = "Sexo") +
  labs(title = "distribución por género en los hogares Colombianos",
       x = "Sexo",
       y = "Unidad de gasto") +
  theme_classic()

  print(graph_1)

```

Nuestra segunda visualización es un gráfico de densidad sobre hombres y mujeres que no hayan llegado a la tercera edad, es decir menores a 60 años

```{r pressure, echo=FALSE}
graph_2 <- filter(df_resto, !is.na(P6020) & P6040 < 60) %>% 
  ggplot(data=. , mapping = aes(x = P6030S3 , group = as.factor(P6020), fill = as.factor(P6020))) + 
  geom_density() + scale_fill_discrete(label = c("1"="hombre" , "2"="mujer") , name = "género") + 
  labs(x = "edad" , y = "",
       title = "Hombres y mujeres que no han llegado a la tercera edad") + 
       theme_dark()
print(graph_2)

```
